#include "maps.h"


#include "constants.h"


RRB_TILE_GOTOX_t *unicorn_position[5] = {
	(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2)),
	(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2)),
	(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 2),
	(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 3),
	(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 4),
};

RRB_TILE_NORMAL_t *unicorn_tiles[2][5] = {
	{
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2)),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2)),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 2),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 3),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 4),
	},
	{
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2)),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2)),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 2),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 3),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 4),
	}
};

RRB_TILE_GOTOX_t  *tail_position[4] = {
	(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2)),
	(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2)),
	(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 2),
	(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 3),
};

RRB_TILE_NORMAL_t *tail_tiles[4] = {
	(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2)),
	(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2)),
	(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 2),
	(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 3),
};

RRB_TILE_GOTOX_t  *mane_position[3] = {
	(RRB_TILE_GOTOX_t *)(TILE_MAP + (45 * 2)),
	(RRB_TILE_GOTOX_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2)),
	(RRB_TILE_GOTOX_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 2),
};

RRB_TILE_NORMAL_t *mane_tiles[3] = {
	(RRB_TILE_NORMAL_t *)(TILE_MAP + (46 * 2)),
	(RRB_TILE_NORMAL_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2)),
	(RRB_TILE_NORMAL_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 2),
};

RRB_TILE_GOTOX_t  *cone_shadow_position[6] = {
	(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 38),
	(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 39),
	(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 40),
	(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 41),
	(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 42),
	(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 43)
};

RRB_TILE_NORMAL_t *cone_shadow_tiles[2][6] = {
	{
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 38),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 39),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 40),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 41),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 42),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 43)
	},
	{
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 38),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 39),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 40),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 41),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 42),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 43)
	}
};

RRB_TILE_GOTOX_t  *cone_position[6] = {
	(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 38),
	(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 39),
	(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 40),
	(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 41),
	(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 42),
	(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 43)
};

RRB_TILE_NORMAL_t *cone_tiles[2][6] = {
	{
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 38),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 39),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 40),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 41),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 42),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 43)
	},
	{
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 38),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 39),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 40),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 41),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 42),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 43)
	}
};

RRB_TILE_GOTOX_t  *icecream_shadow_position[2][38] = {
	{
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 6),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 7),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 8),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 9),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 10),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 11),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 12),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 13),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 14),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 15),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 16),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 17),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 18),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 19),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 20),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 21),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 22),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 23),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 24),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 25),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 26),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 27),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 28),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 29),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 30),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 31),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 32),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 33),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 34),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 35),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 36),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (43 * 2) + (LINE_LENGTH * 2) * 37),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 38),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 39),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 40),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 41),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 42),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 43)
	},
	{
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 6),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 7),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 8),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 9),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 10),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 11),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 12),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 13),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 14),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 15),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 16),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 17),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 18),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 19),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 20),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 21),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 22),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 23),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 24),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 25),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 26),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 27),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 28),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 29),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 30),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 31),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 32),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 33),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 34),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 35),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 36),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (40 * 2) + (LINE_LENGTH * 2) * 37),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 38),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 39),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 40),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 41),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 42),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 43)
	}
};

RRB_TILE_NORMAL_t *icecream_shadow_tiles[2][2][38] = {
	{
		{
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 6),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 7),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 8),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 9),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 10),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 11),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 12),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 13),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 14),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 15),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 16),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 17),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 18),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 19),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 20),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 21),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 22),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 23),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 24),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 25),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 26),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 27),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 28),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 29),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 30),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 31),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 32),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 33),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 34),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 35),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 36),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (44 * 2) + (LINE_LENGTH * 2) * 37),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 38),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 39),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 40),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 41),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 42),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 43)
		},
		{
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 6),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 7),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 8),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 9),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 10),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 11),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 12),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 13),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 14),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 15),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 16),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 17),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 18),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 19),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 20),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 21),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 22),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 23),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 24),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 25),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 26),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 27),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 28),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 29),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 30),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 31),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 32),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 33),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 34),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 35),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 36),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (45 * 2) + (LINE_LENGTH * 2) * 37),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 38),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 39),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 40),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 41),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 42),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 43)
		}
	},
	{
		{
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 6),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 7),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 8),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 9),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 10),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 11),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 12),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 13),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 14),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 15),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 16),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 17),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 18),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 19),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 20),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 21),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 22),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 23),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 24),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 25),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 26),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 27),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 28),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 29),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 30),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 31),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 32),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 33),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 34),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 35),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 36),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (41 * 2) + (LINE_LENGTH * 2) * 37),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 38),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 39),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 40),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 41),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 42),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 43)
		},
		{
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 6),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 7),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 8),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 9),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 10),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 11),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 12),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 13),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 14),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 15),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 16),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 17),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 18),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 19),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 20),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 21),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 22),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 23),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 24),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 25),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 26),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 27),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 28),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 29),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 30),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 31),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 32),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 33),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 34),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 35),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 36),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (42 * 2) + (LINE_LENGTH * 2) * 37),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 38),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 39),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 40),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 41),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 42),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 43)
		}
	}
};

RRB_TILE_GOTOX_t  *small_icecream_shadow_position[2][38] = {
	{
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 6),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 7),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 8),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 9),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 10),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 11),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 12),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 13),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 14),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 15),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 16),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 17),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 18),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 19),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 20),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 21),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 22),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 23),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 24),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 25),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 26),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 27),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 28),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 29),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 30),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 31),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 32),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 33),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 34),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 35),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 36),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (48 * 2) + (LINE_LENGTH * 2) * 37),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 38),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 39),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 40),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 41),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 42),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 43)
	},
	{
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 6),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 7),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 8),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 9),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 10),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 11),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 12),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 13),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 14),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 15),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 16),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 17),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 18),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 19),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 20),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 21),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 22),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 23),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 24),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 25),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 26),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 27),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 28),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 29),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 30),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 31),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 32),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 33),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 34),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 35),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 36),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (46 * 2) + (LINE_LENGTH * 2) * 37),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 38),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 39),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 40),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 41),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 42),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 43)
	}
};

RRB_TILE_NORMAL_t *small_icecream_shadow_tiles[2][38] = {
	{
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 6),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 7),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 8),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 9),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 10),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 11),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 12),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 13),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 14),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 15),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 16),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 17),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 18),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 19),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 20),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 21),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 22),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 23),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 24),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 25),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 26),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 27),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 28),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 29),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 30),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 31),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 32),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 33),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 34),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 35),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 36),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (49 * 2) + (LINE_LENGTH * 2) * 37),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 38),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 39),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 40),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 41),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 42),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 43)
	},
	{
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 6),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 7),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 8),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 9),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 10),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 11),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 12),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 13),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 14),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 15),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 16),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 17),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 18),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 19),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 20),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 21),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 22),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 23),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 24),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 25),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 26),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 27),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 28),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 29),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 30),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 31),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 32),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 33),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 34),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 35),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 36),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (47 * 2) + (LINE_LENGTH * 2) * 37),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 38),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 39),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 40),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 41),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 42),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 43)
	}
};

RRB_TILE_GOTOX_t  *effect_shadow_position[2][38] = {
	{
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 6),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 7),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 8),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 9),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 10),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 11),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 12),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 13),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 14),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 15),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 16),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 17),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 18),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 19),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 20),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 21),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 22),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 23),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 24),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 25),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 26),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 27),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 28),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 29),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 30),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 31),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 32),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 33),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 34),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 35),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 36),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (52 * 2) + (LINE_LENGTH * 2) * 37),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 38),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 39),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 40),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 41),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 42),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 43)
	},
	{
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 6),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 7),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 8),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 9),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 10),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 11),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 12),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 13),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 14),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 15),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 16),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 17),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 18),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 19),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 20),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 21),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 22),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 23),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 24),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 25),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 26),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 27),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 28),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 29),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 30),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 31),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 32),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 33),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 34),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 35),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 36),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (50 * 2) + (LINE_LENGTH * 2) * 37),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 38),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 39),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 40),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 41),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 42),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 43)
	}
};

RRB_TILE_NORMAL_t *effect_shadow_tiles[2][38] = {
	{
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 6),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 7),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 8),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 9),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 10),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 11),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 12),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 13),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 14),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 15),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 16),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 17),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 18),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 19),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 20),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 21),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 22),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 23),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 24),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 25),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 26),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 27),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 28),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 29),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 30),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 31),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 32),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 33),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 34),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 35),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 36),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (53 * 2) + (LINE_LENGTH * 2) * 37),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 38),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 39),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 40),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 41),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 42),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 43)
	},
	{
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 6),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 7),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 8),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 9),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 10),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 11),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 12),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 13),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 14),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 15),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 16),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 17),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 18),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 19),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 20),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 21),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 22),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 23),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 24),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 25),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 26),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 27),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 28),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 29),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 30),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 31),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 32),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 33),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 34),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 35),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 36),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (51 * 2) + (LINE_LENGTH * 2) * 37),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 38),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 39),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 40),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 41),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 42),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 43)
	}
};

// change numbers from here down
RRB_TILE_GOTOX_t  *icecream_position[2][38] = {
	{
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 6),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 7),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 8),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 9),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 10),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 11),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 12),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 13),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 14),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 15),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 16),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 17),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 18),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 19),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 20),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 21),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 22),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 23),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 24),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 25),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 26),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 27),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 28),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 29),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 30),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 31),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 32),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 33),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 34),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 35),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 36),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (57 * 2) + (LINE_LENGTH * 2) * 37),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 38),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 39),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 40),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 41),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 42),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 43)
	},
	{
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 6),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 7),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 8),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 9),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 10),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 11),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 12),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 13),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 14),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 15),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 16),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 17),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 18),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 19),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 20),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 21),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 22),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 23),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 24),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 25),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 26),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 27),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 28),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 29),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 30),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 31),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 32),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 33),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 34),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 35),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 36),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (54 * 2) + (LINE_LENGTH * 2) * 37),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 38),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 39),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 40),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 41),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 42),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 43)
	}
};

RRB_TILE_NORMAL_t *icecream_tiles[2][2][38] = {
	{
		{
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 6),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 7),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 8),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 9),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 10),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 11),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 12),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 13),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 14),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 15),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 16),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 17),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 18),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 19),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 20),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 21),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 22),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 23),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 24),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 25),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 26),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 27),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 28),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 29),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 30),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 31),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 32),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 33),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 34),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 35),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 36),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (58 * 2) + (LINE_LENGTH * 2) * 37),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 38),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 39),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 40),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 41),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 42),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 43)
		},
		{
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 6),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 7),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 8),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 9),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 10),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 11),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 12),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 13),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 14),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 15),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 16),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 17),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 18),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 19),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 20),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 21),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 22),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 23),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 24),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 25),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 26),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 27),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 28),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 29),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 30),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 31),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 32),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 33),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 34),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 35),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 36),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (59 * 2) + (LINE_LENGTH * 2) * 37),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 38),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 39),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 40),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 41),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 42),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 43)
		}
	},
	{
		{
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 6),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 7),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 8),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 9),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 10),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 11),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 12),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 13),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 14),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 15),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 16),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 17),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 18),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 19),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 20),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 21),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 22),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 23),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 24),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 25),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 26),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 27),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 28),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 29),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 30),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 31),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 32),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 33),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 34),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 35),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 36),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (55 * 2) + (LINE_LENGTH * 2) * 37),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 38),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 39),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 40),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 41),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 42),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 43)
		},
		{
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 6),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 7),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 8),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 9),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 10),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 11),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 12),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 13),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 14),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 15),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 16),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 17),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 18),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 19),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 20),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 21),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 22),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 23),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 24),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 25),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 26),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 27),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 28),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 29),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 30),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 31),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 32),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 33),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 34),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 35),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 36),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (56 * 2) + (LINE_LENGTH * 2) * 37),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 38),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 39),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 40),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 41),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 42),
			(RRB_TILE_NORMAL_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 43)
		}
	}
};

RRB_TILE_GOTOX_t  *small_icecream_position[2][38] = {
	{
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 6),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 7),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 8),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 9),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 10),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 11),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 12),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 13),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 14),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 15),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 16),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 17),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 18),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 19),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 20),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 21),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 22),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 23),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 24),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 25),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 26),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 27),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 28),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 29),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 30),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 31),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 32),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 33),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 34),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 35),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 36),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (62 * 2) + (LINE_LENGTH * 2) * 37),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (68 * 2) + (LINE_LENGTH * 2) * 38),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (68 * 2) + (LINE_LENGTH * 2) * 39),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (68 * 2) + (LINE_LENGTH * 2) * 40),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (68 * 2) + (LINE_LENGTH * 2) * 41),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (68 * 2) + (LINE_LENGTH * 2) * 42),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (68 * 2) + (LINE_LENGTH * 2) * 43)
	},
	{
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 6),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 7),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 8),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 9),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 10),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 11),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 12),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 13),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 14),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 15),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 16),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 17),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 18),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 19),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 20),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 21),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 22),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 23),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 24),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 25),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 26),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 27),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 28),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 29),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 30),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 31),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 32),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 33),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 34),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 35),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 36),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (60 * 2) + (LINE_LENGTH * 2) * 37),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 38),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 39),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 40),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 41),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 42),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 43)
	}
};

RRB_TILE_NORMAL_t *small_icecream_tiles[2][38] = {
	{
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 6),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 7),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 8),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 9),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 10),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 11),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 12),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 13),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 14),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 15),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 16),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 17),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 18),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 19),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 20),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 21),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 22),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 23),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 24),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 25),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 26),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 27),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 28),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 29),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 30),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 31),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 32),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 33),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 34),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 35),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 36),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (63 * 2) + (LINE_LENGTH * 2) * 37),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (69 * 2) + (LINE_LENGTH * 2) * 38),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (69 * 2) + (LINE_LENGTH * 2) * 39),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (69 * 2) + (LINE_LENGTH * 2) * 40),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (69 * 2) + (LINE_LENGTH * 2) * 41),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (69 * 2) + (LINE_LENGTH * 2) * 42),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (69 * 2) + (LINE_LENGTH * 2) * 43)
	},
	{
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 6),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 7),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 8),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 9),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 10),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 11),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 12),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 13),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 14),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 15),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 16),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 17),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 18),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 19),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 20),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 21),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 22),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 23),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 24),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 25),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 26),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 27),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 28),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 29),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 30),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 31),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 32),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 33),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 34),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 35),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 36),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (61 * 2) + (LINE_LENGTH * 2) * 37),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 38),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 39),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 40),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 41),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 42),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 43)
	}
};

RRB_TILE_GOTOX_t  *effect_position[2][38] = {
	{
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 6),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 7),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 8),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 9),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 10),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 11),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 12),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 13),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 14),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 15),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 16),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 17),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 18),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 19),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 20),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 21),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 22),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 23),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 24),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 25),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 26),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 27),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 28),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 29),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 30),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 31),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 32),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 33),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 34),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 35),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 36),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (66 * 2) + (LINE_LENGTH * 2) * 37),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (72 * 2) + (LINE_LENGTH * 2) * 38),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (72 * 2) + (LINE_LENGTH * 2) * 39),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (72 * 2) + (LINE_LENGTH * 2) * 40),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (72 * 2) + (LINE_LENGTH * 2) * 41),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (72 * 2) + (LINE_LENGTH * 2) * 42),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (72 * 2) + (LINE_LENGTH * 2) * 43)
	},
	{
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 6),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 7),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 8),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 9),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 10),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 11),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 12),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 13),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 14),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 15),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 16),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 17),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 18),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 19),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 20),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 21),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 22),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 23),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 24),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 25),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 26),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 27),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 28),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 29),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 30),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 31),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 32),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 33),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 34),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 35),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 36),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (64 * 2) + (LINE_LENGTH * 2) * 37),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (70 * 2) + (LINE_LENGTH * 2) * 38),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (70 * 2) + (LINE_LENGTH * 2) * 39),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (70 * 2) + (LINE_LENGTH * 2) * 40),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (70 * 2) + (LINE_LENGTH * 2) * 41),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (70 * 2) + (LINE_LENGTH * 2) * 42),
		(RRB_TILE_GOTOX_t *)(TILE_MAP + (70 * 2) + (LINE_LENGTH * 2) * 43)
	}
};

RRB_TILE_NORMAL_t *effect_tiles[2][38] = {
	{
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 6),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 7),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 8),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 9),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 10),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 11),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 12),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 13),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 14),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 15),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 16),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 17),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 18),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 19),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 20),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 21),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 22),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 23),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 24),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 25),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 26),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 27),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 28),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 29),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 30),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 31),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 32),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 33),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 34),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 35),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 36),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (67 * 2) + (LINE_LENGTH * 2) * 37),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (73 * 2) + (LINE_LENGTH * 2) * 38),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (73 * 2) + (LINE_LENGTH * 2) * 39),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (73 * 2) + (LINE_LENGTH * 2) * 40),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (73 * 2) + (LINE_LENGTH * 2) * 41),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (73 * 2) + (LINE_LENGTH * 2) * 42),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (73 * 2) + (LINE_LENGTH * 2) * 43)
	},
	{
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 6),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 7),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 8),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 9),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 10),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 11),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 12),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 13),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 14),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 15),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 16),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 17),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 18),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 19),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 20),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 21),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 22),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 23),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 24),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 25),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 26),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 27),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 28),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 29),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 30),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 31),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 32),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 33),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 34),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 35),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 36),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (65 * 2) + (LINE_LENGTH * 2) * 37),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (71 * 2) + (LINE_LENGTH * 2) * 38),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (71 * 2) + (LINE_LENGTH * 2) * 39),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (71 * 2) + (LINE_LENGTH * 2) * 40),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (71 * 2) + (LINE_LENGTH * 2) * 41),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (71 * 2) + (LINE_LENGTH * 2) * 42),
		(RRB_TILE_NORMAL_t *)(TILE_MAP + (71 * 2) + (LINE_LENGTH * 2) * 43)
	}
};
